|<h2>Course:</h2>|<h1><a href="https://udemy.com/course/deeplearning_x/?couponCode=202508" target="_blank">A deep understanding of deep learning</a></h1>|
|-|:-:|
|<h2>Section:</h2>|<h1>Math, numpy, pytorch<h1>|
|<h2>Lecture:</h2>|<h1><b>Identical randomness via seeding<b></h1>|

<br>

<h5><b>Teacher:</b> Mike X Cohen, <a href="https://sincxpress.com" target="_blank">sincxpress.com</a></h5>
<h5><b>Course URL:</b> <a href="https://udemy.com/course/deeplearning_x/?couponCode=202508" target="_blank">udemy.com/course/deeplearning_x/?couponCode=202508</a></h5>
<i>Using the code without the course may lead to confusion or errors.</i>

In [ ]:
# import libraries
import numpy as np
import torch

In [ ]:
# generate a few random numbers
np.random.randn(5)

In [ ]:
# repeat after fixing the seed (old-but-still-widely-used method)
np.random.seed(17)
print(np.random.randn(5))
print(np.random.randn(5))

# [ 0.27626589 -1.85462808  0.62390111  1.14531129  1.03719047]
# [ 1.88663893 -0.11169829 -0.36210134  0.14867505 -0.43778315]

# New seed mechanism in numpy

In [ ]:
randseed1 = np.random.RandomState(17)
randseed2 = np.random.RandomState(20210530)

print(randseed1.randn(5))  # same sequence
print(randseed2.randn(5))  # different from above, but same each time
print(randseed1.randn(5))  # same as two up
print(randseed2.randn(5))  # same as two up
print(np.random.randn(5))  # different every time

# [ 0.27626589 -1.85462808  0.62390111  1.14531129  1.03719047]
# [-0.24972681 -1.01951826  2.23461339  0.72764703  1.2921122 ]
# [ 1.88663893 -0.11169829 -0.36210134  0.14867505 -0.43778315]
# [ 1.15494929 -0.0015467  -0.11196868 -1.08136725  0.10265891]
# [ 2.171257    1.15231025 -1.81881234 -0.13804934  0.53983961]

# Now in pytorch

In [ ]:
torch.randn(5)

In [ ]:
torch.manual_seed(17)
print(torch.randn(5))

# torch's seed doesn't spread to numpy
print(np.random.randn(5))