In [3]:
import numpy as np

numbers = [1, 2, 3, 4, 5]

np.mean(numbers)

np.float64(3.0)

In [4]:
np.linspace(1, 7, 5)

array([1. , 2.5, 4. , 5.5, 7. ])

In [5]:
x = np.linspace(1, 7, 5)
type(x)

numpy.ndarray

In [13]:
numbers_np = np.array(numbers)
print(type(numbers))
print(type(numbers_np))

<class 'list'>
<class 'numpy.ndarray'>


In [16]:
print(numbers_np.min())

1


In [17]:
print(np.min(numbers_np))

1


In [18]:
print(np.min(numbers))

1


In [20]:
np.min(numbers)

np.int64(1)

In [21]:
# in-place
# out-of-place / not in-place operations

n = [4, 3, 5, 2, 6, 1, 7]

print(n)
n.sort()
print(n)

[4, 3, 5, 2, 6, 1, 7]
[1, 2, 3, 4, 5, 6, 7]


In [24]:
n = [4, 3, 5, 2, 6, 1, 7]
nn = np.array(n)

print(nn)
nn.sort()
print(nn)

[4 3 5 2 6 1 7]
[1 2 3 4 5 6 7]


In [25]:
n = [4, 3, 5, 2, 6, 1, 7]
nn = np.array(n)

print(nn)
np.sort(nn)
print(nn)

[4 3 5 2 6 1 7]
[4 3 5 2 6 1 7]


In [26]:
n = [4, 3, 5, 2, 6, 1, 7]
nn = np.array(n)

print(nn)
nns = np.sort(nn)
print(nns)

[4 3 5 2 6 1 7]
[1 2 3 4 5 6 7]
